version: "3"

services:
  head:
      image: openmpi:latest
      tty: true
      user: mpi_user
      ports: 
        - "22"
      links:
        - "node"
      volumes:
        - $PWD:/mnt

  node:
      image: openmpi:latest
      tty: true
      user: mpi_user
      volumes:
        - $PWD:/mnt
